---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или
    категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность добавлять товары в корзину и
    просматривать содержимое корзины
  - Пользователь должен иметь возможность просматривать товары и просматривать
    подробную информацию о товаре
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и
    оптимизирован для скорости работы
  - Сайт должен иметь мобильную версию
  - Сайт должен быть протестирован на совместимость с последними версиями
    браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
  - Сайт должен быть безопасным и защищать данные пользователя
implicit:
  - Пользователь должен иметь возможность выбрать форму оплаты
  - Пользователь должен иметь возможность выбрать способ оплаты
  - Функция дополнительного подтверждения оплаты заказа при его оформлении
  - Пользователь должен иметь возможность выбрать способ получения товара
  - Пользователь должен иметь возможность оформить возврат товара
  - Пользователь должен иметь возможность оставить отзыв о товаре
  - Пользователь должен иметь возможность просмотра информации по своим заказам
  - пользователь не может редактировать описание и цену товара
